name: QMK Corne Build

on:
  push:
    branches:
      - miryoku_custom
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up QMK
      uses: qmk/qmk_firmware-action@main

    - name: Compile left half
      run: qmk compile -kb crkbd/r2g -km miryoku_custom -bl dfu-split-left

    - name: Compile right half
      run: qmk compile -kb crkbd/r2g -km miryoku_custom -bl dfu-split-right

    - name: Rename firmware
      run: |
        mv crkbd_r2g_miryoku_custom_dfu-split-left.bin corne_left.bin
        mv crkbd_r2g_miryoku_custom_dfu-split-right.bin corne_right.bin
      continue-on-error: true

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: corne-firmware
        path: |
          corne_left.bin
          corne_right.bin
